In [1]:
import numpy as np
from numpy.linalg import eig
from math import sqrt

In [2]:
A = np.array([[3., complex(0., 2.)], [complex(0.,-2.), 0.]])
A

array([[3.+0.j, 0.+2.j],
       [0.-2.j, 0.+0.j]])

In [3]:
w, v = eig(A)

In [19]:
c_2_1 = complex(0., -1./sqrt(5))
c_2_2 = complex(2./sqrt(5), 0.)

In [20]:
c_1_1 = complex(0., 2/sqrt(5))
c_1_2 = complex(1./sqrt(5), 0.)

In [21]:
C = np.array([[c_1_1, c_2_1], [c_1_2, c_2_2]])
C

array([[0.        +0.89442719j, 0.        -0.4472136j ],
       [0.4472136 +0.j        , 0.89442719+0.j        ]])

In [22]:
(C.conjugate().T).dot(A).dot(C)

array([[ 4.00000000e+00+0.j,  0.00000000e+00+0.j],
       [-5.55111512e-17+0.j, -1.00000000e+00+0.j]])

In [23]:
C

array([[0.        +0.89442719j, 0.        -0.4472136j ],
       [0.4472136 +0.j        , 0.89442719+0.j        ]])

In [24]:
v

array([[-0.89442719+0.j       ,  0.        -0.4472136j],
       [ 0.        +0.4472136j,  0.89442719+0.j       ]])

In [25]:
v[:, 0] *= complex(0., -1.)

In [26]:
v

array([[0.        +0.89442719j, 0.        -0.4472136j ],
       [0.4472136 +0.j        , 0.89442719+0.j        ]])