## Method 1

In [6]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import solve as np_solve

In [26]:
A = np.array([[3, 4], [1, 3]])
A

array([[3, 4],
       [1, 3]])

In [27]:
det(A)

5.000000000000001

In [28]:
b = np.array([-1, 2])
b

array([-1,  2])

In [29]:
np_solve(A, b)

array([-2.2,  1.4])